services:
  homepage:
    image: nginx:alpine
    container_name: homepage
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./static:/usr/share/nginx/html/static
    ports:
      - 2180:80
    restart: always